#!/usr/bin/env bash
# there can be only one...way to include output when recieving a SIGTERM signal
trap 'echo "I am invincible!!!"' 15
n=1
while [ $n = 1 ]
do
	echo "To infinity and beyond"
sleep 2
done
