#!/usr/bin/env bash
# using while loop with an if statement for conditional statement
n=1
while [ $n -gt 10 ]
do
	echo "Best School"
	(( n++ ))
	if [ $n == 9 ]
	then
	echo "Hi"
	fi
	echo "Best School"
done
