#!/usr/bin/env bash
# using while loops with case statements
n=1
while [ $n -le 20 ]
do
	echo "$n"
	case $n in
		4) 
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
		(( n++ ))
done
