#!/usr/bin/env bash
# using file test operators with if and else
file="school"
if [ -e $file ]
then
	printf "school file exists"

	if [ -s $file ]
	then
		printf "school file is not empty"
	else
		printf "school file is empty"
	fi
	
	if [ -f $file ]
	then
		printf "school file is a regular file"
	fi
else
	printf "school file does not exist"
fi

